### ISSUE TITLE
Add docs / readme for how to override prettier/prettier rules

### ISSUE THREAD

**Issue by ghost** [expo/eslint-config-universe#19]
There should be a section of the README explaining how you've changed the default Prettier rules and how to override them as I've demonstrated in #18

**Comment by ankhzet** [comment]
Also, there there should be a section of the README explaining how to opt-out from usage of "prettier" entirely.

**Comment by ide** [comment]
You should be able to just define a .prettierrc to provide custom config. As for opting out of Prettier, you might be able to import the specific configs (e.g. under `shared`) and build up a config object yourself but YMMV.
