### ISSUE TITLE
"extends": "expo/react" is not working

### ISSUE THREAD

**Issue by shamsfk** [expo/eslint-config-universe#2]
"extends": "expo/react" throws config error
while "extends": "expo" is working perfectly with exception of being unusable with React's JSX (which defies the purpose of a whole config?)
I'm using Atom editor (by the way, it threw an "eslint-plugin-flowtype" error, so I installed it (you probably should mention it in the readme)

**Comment by shamsfk** [comment]
Ok, I managed to get it running by copying contents of react.js to my .eslintrc.js and modifying extends to 'expo'.

But man that was untrivial for a newbie.

**Comment by shamsfk** [comment]
And react/jsx-no-bind rule currently prevents usage of fat arrow functions, was it intentional?

**Comment by ide** [comment]
Thanks for trying out our linter config. We just updated the linter config significantly, including Prettier support and it allows arrow functions in JSX. If you'd like to try it out, run:

`npm install --dev eslint-config-universe@1.0.1 eslint prettier`

You don't need to install eslint-plugin-... things anymore.

In your package.json/.eslintrc.js, add `"extends": "universe/native"` (there are also `universe`, `universe/web`, and `universe/node` too).

**Comment by ide** [comment]
I'm going to close this since the linter configuration has changed a lot since this issue was opened. Let us know if you run into a similar issue again.
