### ISSUE TITLE
NPM package name?

### ISSUE THREAD

**Issue by alexkrolick** [expo/eslint-config-universe#3]
https://www.npmjs.com/search?q=eslint-config-expo

Is it `eslint-config-universe` or `eslint-config-expo`? The installation instructions say `eslint-config-expo`.

**Comment by ide** [comment]
Sorry, the readme is out of date. The package is eslint-config-universe.

**Comment by xzilja** [comment]
Addressed this in pr #4

**Comment by ide** [comment]
We've synced out our latest commits (and fixed the server that does this), thank you for the issue and PR!
