### ISSUE TITLE
no-unused-vars

### ISSUE THREAD

**Issue by lucasapereira** [expo/eslint-config-universe#7]
EsLint is giving me no-unused-vars for things that I am using in the JSX

**Comment by lucasapereira** [comment]
Sorry, my mistake...

**Comment by lucasapereira** [comment]
Sorry, my mistake...

**Comment by martinezguillaume** [comment]
Hi, how do you solve the problem ? 😅

**Comment by lucasapereira** [comment]
Hello, I was using in the package.json
{
  "eslintConfig": {
    // Choose from universe/native, universe/node, universe/web
    "extends": "universe"
  }
}

instead of 
{
  "eslintConfig": {
    // Choose from universe/native, universe/node, universe/web
    "extends": "universe/web"
  }
}
or in the .eslintrc.js

module.exports = {
  extends: 'universe',
};
instead of 
module.exports = {
  extends: 'universe/web',
};

**Comment by martinezguillaume** [comment]
Nice ! I put
```js
module.exports = {
  extends: 'universe/native',
};
```
instead of
```js
module.exports = {
  extends: 'universe',
};
```
to `.eslintrc.js` and it works, thanks !
