### ISSUE TITLE
Add no-unresolved as default?

### ISSUE THREAD

**Issue by xzilja** [expo/eslint-config-universe#8]
I hadd to add `"import/no-unresolved": 2` to my config rules to make sure I get an error when I'm importing something that can't be resolved path wise.

Do you guys think this would be a useful rule to have as default in this config?

**Comment by ide** [comment]
We omitted this because there are cases where imports & requires in the source file can't be resolved but they can be in the built/compiled files. As you might have discovered, ESLint lets you override rules in your own configuration if you'd like:

```json
{
  "extends": "universe/native",
  "rules": {
    "import/no-unresolved": "error"
  }
}
```
