### ISSUE TITLE
Add error only configs

### ISSUE THREAD

**Issue by yleflour** [expo/eslint-config-universe#9]
First of all, thank you for this project. The config is top notch and we can finally remove the eslint clutter we had.

My only issue is that when working with rookies, I would like to be able to enforce every rule as errors instead of warnings. Is there an easy way to do so without rewriting every rule?

**Comment by ide** [comment]
I'm not sure if this is possible but you can specify `--max-warnings 0` in CI and eslint will exit with a non-zero code if there are any warnings.
